# Generated by Django 5.2.10 on 2026-02-15 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_movie_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='currency',
        ),
    ]
