# Generated by Django 5.2.10 on 2026-02-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_remove_movie_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('EURO', 'EUR'), ('DOLLAR', 'DOL'), ('RUB', 'RUB')], default='DOLLAR', max_length=6, verbose_name='валюта'),
        ),
    ]
