# Generated by Django 5.2.10 on 2026-02-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_movie_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer', models.CharField(max_length=100, verbose_name='Режиссер')),
                ('producer_email', models.EmailField(max_length=50, verbose_name='email')),
            ],
        ),
    ]
