# Generated by Django 5.2.10 on 2026-02-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_producer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producer',
        ),
    ]
