# Generated by Django 5.2.10 on 2026-02-16 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie_app.producer'),
        ),
    ]
