# Generated by Django 5.2.10 on 2026-02-06 19:07

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categorymodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(verbose_name='Альт. заголовок')),
                ('image', models.ImageField(default='default/not_found.png', upload_to='post/%Y/%m/%d', verbose_name='Изображение поста')),
                ('short_body', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=350, verbose_name='Краткое описание')),
                ('full_body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержимое поста')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Опубликовано')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('ЧЕ', 'Черновик'), ('ОП', 'Опубликовано')], default='ЧЕ', max_length=2, verbose_name='Статус')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post', to='blog.categorymodel', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-publish'],
                'indexes': [models.Index(fields=['-publish'], name='blog_postmo_publish_0e928c_idx')],
            },
        ),
    ]
